### ISSUE TITLE
getting Error : File not found while importing scan (obj zip file)

### ISSUE THREAD

**Issue by sntarkas** [Ugani-Prosthetics/ufit-blender#44] opened 2023-12-01 07:54 UTC
![Error_uFit](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/a84b36a6-a6f7-4a08-a0d3-8c9f7090a1e6)

**Comment by bert-ugani** [comment] 2023-12-01 07:57
Hi sntarkas, would it be possible to send me the file you are using? 
If you are restricted to privacy rules, you can forward it to bert@ugani.org and I'll remove the information once tested

**Comment by sntarkas** [comment] 2023-12-01 08:03
I have tried using the demo scan( John Doe) , scan_emily_davis example file as well as 
[Easiofy_Model.zip](https://github.com/Ugani-Prosthetics/ufit-blender/files/13522568/Easiofy_Model.zip)

**Comment by bert-ugani** [comment] 2023-12-01 08:11
Hi, I am not encountering any issues loading the Easify_Model.zip file. 
Would it be possible to:
1. provide me the exact error message you get?
2. provide me a screenshot of all the addons enabled in your Blender environment?
3. tell me which operating system you are using?

Here is an example of how to find all enabled addons:
![image](https://github.com/Ugani-Prosthetics/ufit-blender/assets/138581427/c728f6c3-2ed4-4615-98fa-25e536d0815b)

**Comment by bert-ugani** [comment] 2023-12-01 08:49
For testing purposes, I have attached a new version here where debug is enabled.
To install this version:
1. uninstall the other uFit version (remove!)
2. restart Blender
3. install this version
4. restart Blender

This is an unstable version that did not undergo the full testing cycle. So unexpected behaviour is possible but we can use it now for further debugging the problem. 

[ufit-2.0.0-beta.zip](https://github.com/Ugani-Prosthetics/ufit-blender/files/13522982/ufit-2.0.0-beta.zip)

**Comment by sntarkas** [comment] 2023-12-01 11:49
Hi 
I am attaching all the screenshots. And I am using windows 11.
![addons](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/6f160071-9dd2-4ec3-a116-05b19e851730)
![addons1](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/166eb99f-27a8-49fe-a0b3-2895bd5459af)
![Error](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/05b81a11-ddcd-4022-92c6-8965cbacefe6)

**Comment by sntarkas** [comment] 2023-12-04 05:27
when I installed this beta version my blender crashes

**Comment by bert-ugani** [comment] 2023-12-04 07:47
Hi sntarkas,

To help us investigate the issue and resolve the problem, could you please provide (in all your messages) more detail? Specifically, we need the following information:
- Detailed error messages
- Steps to reproduce the issue (if possible)
- Any specific configurations you are using

Without this information it is not possible to further investigate. Your cooperation will greatly assist us in resolving this matter.

**Comment by sntarkas** [comment] 2023-12-04 13:51
Hi,
As soon as I start the Ufit addon (I have tried all available versions 2.0 beta, 1.2,1.1)  in blender 4.0.1(latest version) then the blender crashes. I dont get any error message. I have also reinstalled blender as I was using the previously blender 3.6

**Comment by bert-ugani** [comment] 2023-12-05 20:44
Hi, the versions of uFit is only tested until Blender 3.5.1 
In the next official release we also make sure uFit is supported in Blender 3.6 as well.

**Comment by sntarkas** [comment] 2023-12-11 11:19
I have tried it on blender 3.5.1 as suggested by you but it is showing context missing error
![11 12 2023_16 42 09_REC](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/3769944a-0a55-4404-ab11-9ee9f38b38b3)

**Comment by bert-ugani** [comment] 2023-12-15 18:47
Hi, regretfully I am not able to replicate the problem. No other users are facing the same issue.
You previously stated that Blender instantly crashed, we have solved that issue now. It was related to a full screen mode that was auto triggered on startup.

**Comment by bert-ugani** [comment] 2023-12-15 18:47
On our website you can now download v2.0.0. It is considered the most stable release tested on Blender 3.5.0 and 3.5.1

**Comment by sntarkas** [comment] 2023-12-19 08:48
Thanks @bert-ugani for your continuous support and guidance. Now I am able to install v2.0.0 in blender 3.5.1.Also I am able to go on all steps but not able to apply push/pull on mesh, pull bottom nor the base thickness or extra thickness  not even the connector is visible
[Uploading transtibial_231216_185932_error.zip…]()

**Comment by YouSaveCreation** [comment] 2024-05-25 22:45
Thank you for giving me the opportunity to try the U-Fit addons in Blender. after I followed the course instructions. there are several problems:
1. in the video add circumference. When the arrow points upwards to provide cuts 3 cm apart, the cut line cannot be seen and when the next button is pressed an error appears.
2. in Video Sculft (Push & Pull). after following the instructions and pressing the Next button there was no change in shape even though the factor was changed to 30 mm)
I'm using Blender 3.5.0 (portable) and U-Fit 2.0.1
Please provide guidance and solutions.
Thank You

**Comment by YouSaveCreation** [comment] 2024-05-26 13:51
> Thank you for giving me the opportunity to try the U-Fit addons in Blender. after I followed the course instructions. there are several problems:
> 
> 1. in the video add circumference. When the arrow points upwards to provide cuts 3 cm apart, the cut line cannot be seen and when the next button is pressed an error appears.
> 2. in Video Sculft (Push & Pull). after following the instructions and pressing the Next button there was no change in shape even though the factor was changed to 30 mm)
>    I'm using Blender 3.5.0 (portable) and U-Fit 2.0.1
>    Please provide guidance and solutions.
>    Thank You

Already Solved....due to during import file , scaling need to change from 1 to 0.01 (Thanks Pak Eric ;))

**Closed** 2024-07-16 08:41 UTC
